name: PR

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          node-version: 24
          pnpm-version: 10.25

      - run: pnpm check:types
      - run: pnpm lint
      - run: pnpm test
      - uses: codecov/codecov-action@v2.1.0
      - uses: EndBug/add-and-commit@v7
        if: ${{ failure() && github.actor == 'renovate' }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          node-version: 24
          pnpm-version: 10.25

      - uses: superdispatch/actions/build-size/limit@v1
        with:
          install_command: 'pnpm install'
          build_command: 'pnpm build'

  preview:
    runs-on: ubuntu-latest

    outputs:
      deploy-url: ${{ steps.deploy.outputs.details_url }}

    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          node-version: 24
          pnpm-version: 10.25

      - run: pnpm storybook:build
      - run: pnpm playroom:build
      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: superdispatch-ui
          channelId: ${{ github.event.number }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.FIREBASE_PROJECT }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_HOSTING_SERVICE_ACCOUNT_JSON }}
          firebaseToolsVersion: '12.9.1'

  e2e:
    needs:
      - checks
      - preview
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          node-version: 24
          pnpm-version: 10.25

      - run: pnpm cypress install
      - run: pnpm cypress run
        env:
          CYPRESS_HOST: ${{ needs.preview.outputs.deploy-url }}

  visual-testing:
    needs:
      - checks
      - preview
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          node-version: 24
          pnpm-version: 10.25

      - uses: superdispatch/actions/update-snapshots@v1.5
        with:
          command: pnpm test-visual-ci ${{ needs.preview.outputs.deploy-url }}
          update-command: pnpm visual-update-ci ${{ needs.preview.outputs.deploy-url }}
